import React, { createContext, useContext, useState, useEffect } from 'react';

export const LANGUAGES = [
  { code: 'en', name: 'English', native: 'English', flag: '🇬🇧', voiceCode: 'en-IN' },
  { code: 'hi', name: 'Hindi', native: 'हिंदी', flag: '🇮🇳', voiceCode: 'hi-IN' },
  { code: 'hinglish', name: 'Hinglish', native: 'Hinglish', flag: '🇮🇳', voiceCode: 'hi-IN' },
  { code: 'bn', name: 'Bengali', native: 'বাংলা', flag: '🇮🇳', voiceCode: 'bn-IN' },
  { code: 'mr', name: 'Marathi', native: 'मराठी', flag: '🇮🇳', voiceCode: 'mr-IN' },
  { code: 'te', name: 'Telugu', native: 'తెలుగు', flag: '🇮🇳', voiceCode: 'te-IN' },
  { code: 'ta', name: 'Tamil', native: 'தமிழ்', flag: '🇮🇳', voiceCode: 'ta-IN' },
  { code: 'gu', name: 'Gujarati', native: 'ગુજરાતી', flag: '🇮🇳', voiceCode: 'gu-IN' },
  { code: 'kn', name: 'Kannada', native: 'ಕನ್ನಡ', flag: '🇮🇳', voiceCode: 'kn-IN' },
  { code: 'ml', name: 'Malayalam', native: 'മലയാളം', flag: '🇮🇳', voiceCode: 'ml-IN' },
];

const translations = {
  en: {
    appName: "NariCare AI",
    tagline: "Your AI-Powered Women's Healthcare Companion",
    heroDescription: "Empowering women with safe, personalized and accessible healthcare through AI.",
    login: "Login",
    signup: "Sign Up",
    learnMore: "Learn More",
    logout: "Logout",
    selectLanguage: "Select Preferred Language",
    welcomeTitle: "Welcome to NariCare AI",
    welcomeSubtitle: "Choose your primary language to personalize your healthcare journey.",
    navDashboard: "Dashboard",
    navNearby: "Find Healthcare",
    navAINavigator: "AI Navigator",
    navTimeline: "Health Records",
    navReminders: "Reminders",
    navMenstrual: "Menstrual Care",
    navPregnancy: "Pregnancy",
    navEducation: "Education",
    navProfile: "Profile & Settings",
    goodMorning: "Good Morning",
    goodAfternoon: "Good Afternoon",
    goodEvening: "Good Evening",
    todaysTip: "Today's Women's Health Tip",
    nextReminder: "Next Pill & Hydration Alert",
    upcomingAppointment: "Upcoming Doctor Appointment",
    currentCycle: "Current Cycle Phase",
    day: "Day",
    follicular: "Follicular Phase",
    ovulation: "Fertile Window",
    luteal: "Luteal Phase",
    menstrual: "Menstrual Phase",
    landing: {
      promptBanner: "Select your preferred language:",
      currentlyIn: "Currently in",
      changeLang: "Change Language",
      heroBadge: "Next-Gen Women's Healthcare Platform",
      heroSub: "Designed specifically for women across India with 10 native languages, intelligent symptom checker, and trusted female doctors.",
      goToDashboard: "Go to Dashboard",
      safeConfidential: "Safe & Confidential",
      indianLanguages: "Indian Languages",
      aiMedicalGuidance: "AI Medical Guidance",
      verifiedFemaleDoctors: "Verified Female Doctors",
      connectGynaecologists: "Connect with top gynecologists near you",
      careEngineTitle: "Comprehensive Care Engine",
      careEngineHeading: "Everything Every Woman Needs for Complete Health & Care",
      careEngineSub: "From monthly cycle tracking to emergency hospital care and AI symptom diagnosis, NariCare AI is built for every stage of a woman's life.",
      exploreFeature: "Explore Feature",
      motherTongueTitle: "Healthcare in Your Mother Tongue",
      motherTongueSub: "No language barriers. Use NariCare AI effortlessly in English, Hindi, Hinglish, Bengali, Marathi, Telugu, Tamil, Gujarati, Kannada, or Malayalam."
    },
    featureCards: {
      aiNavTitle: "AI Health Navigator",
      aiNavDesc: "Clinical-grade symptom analysis, instant risk triage & personalized action plans.",
      nearbyTitle: "Nearby Healthcare",
      nearbyDesc: "Find verified female doctors, book doorstep blood diagnostics & safe medical rides.",
      timelineTitle: "Health Timeline",
      timelineDesc: "Secure digital health records, past lab reports, and AI diagnostic insights.",
      remindersTitle: "Smart Reminders",
      remindersDesc: "Timely alerts for supplements, water intake, doctor visits & period tracking.",
      menstrualTitle: "Menstrual Care",
      menstrualDesc: "Ovulation forecasting, symptom logging, and period wellness analytics.",
      pregnancyTitle: "Pregnancy Companion",
      pregnancyDesc: "Week-by-week trimester guidance, bump photo journal, and kick counter.",
      educationTitle: "AI Health Education",
      educationDesc: "Bite-sized articles, myth busters & video guides curated by top female obstetricians."
    },
    cards: {
      nearby: "Find Healthcare Near You",
      nearbySub: "Verified female doctors, lab tests at home & transport",
      aiNav: "AI Health Navigator",
      aiNavSub: "Instant symptom analysis, triage & smart recommendations",
      timeline: "Health Timeline",
      timelineSub: "Digital health records, prescriptions & lab vault",
      reminders: "Smart Reminders",
      remindersSub: "Medication alerts, period tracker & hydration",
      menstrual: "Menstrual Care",
      menstrualSub: "Cycle insights, fertility window & symptom logging",
      pregnancy: "Pregnancy Companion",
      pregnancySub: "Week-by-week guide, bump photos & kick counter",
      pregnancyDisabledMsg: "Planning pregnancy or currently expecting?",
      enableButton: "Enable Companion",
      education: "AI Health Education",
      educationSub: "Multilingual health articles, myth-busters & podcasts",
      profile: "Profile & Settings",
      profileSub: "Language, permissions, emergency contacts & preferences"
    },
    chatbot: {
      title: "Nari AI Assistant",
      subtitle: "Ask me anything about women's health, symptoms, or remedies",
      placeholder: "Ask Nari anything about your health...",
      speaking: "Nari is speaking...",
      listening: "Listening to your voice...",
      voiceInput: "Tap to Speak",
      stopVoice: "Stop Listening",
      suggestedHeader: "Suggested Questions"
    },
    timeline: {
      title: "Digital Health Records & Timeline",
      subtitle: "Your secure vault for lab reports, prescriptions, and AI explanations.",
      uploadButton: "Upload Health Record",
      sampleReports: "Health Records",
      viewReport: "View & Interpret",
      aiAnalysis: "AI Health Analysis",
      allClear: "Normal Range",
      attentionNeeded: "Review Advised",
      documentTitle: "Document Title",
      prescribingDoctor: "Prescribing Doctor / Lab",
      category: "Record Category",
      selectFile: "Select File from Computer",
      notesOptional: "Report Test Results / Notes (Optional)",
      uploading: "Uploading...",
      cancel: "Cancel",
      saveVault: "Save to Vault & Analyze"
    },
    menstrualPage: {
      title: "Menstrual Cycle & Fertility Tracker",
      subtitle: "Predict cycle phases, track symptoms, and receive AI-backed reproductive guidance.",
      currentPhase: "Current Phase",
      fertileWindow: "Fertile Window",
      logSymptoms: "Log Today's Symptoms",
      aiInsight: "Nari AI Cycle Summary"
    },
    pregnancyPage: {
      title: "Pregnancy Companion & Fetal Tracker",
      subtitle: "Week-by-week guidance, kick tracking, and personalized maternal wellness tips.",
      gestationalWeek: "Gestational Week",
      dueDate: "Estimated Due Date",
      kickCounter: "Kick Counter Today",
      weeklyGuide: "Weekly Milestones"
    },
    nearbyPage: {
      title: "Nearby Healthcare & Teleconsultation",
      subtitle: "Find top-rated female gynecologists, home sample collection, and transport.",
      filterFemaleDoctors: "Female Doctors Only",
      homeDiagnostics: "Home Sample Pickup Available",
      transportAssistance: "Hospital Transport Service",
      bookAppointment: "Book Appointment",
      callEmergency: "Call Helpline"
    },
    educationPage: {
      title: "AI Health Education & Knowledge Vault",
      subtitle: "Doctor-verified health articles, myth-busters, and wellness audio guides.",
      readArticle: "Read Full Guide",
      mythBusters: "Myth vs. Fact",
      podcasts: "Listen to Podcast"
    },
    remindersPage: {
      title: "Smart Medication & Hydration Reminders",
      subtitle: "Never miss your supplements, hydration goal, or follow-up doctor appointments.",
      addReminder: "Add Custom Reminder",
      pillAlert: "Supplement Alert",
      hydrationAlert: "Hydration Target",
      activeReminders: "Active Notifications"
    },
    profilePage: {
      title: "Profile & Personal Settings",
      subtitle: "Manage your health preferences, global language, and data permissions.",
      personalInfo: "Personal Details",
      languagePref: "Global Preferred Language",
      permissions: "App & Device Permissions",
      emergencyContacts: "Emergency Contact Numbers",
      saveChanges: "Save Profile Preferences"
    },
    auth: {
      welcomeBack: "Welcome Back to NariCare",
      signinSub: "Sign in to access your personalized NariCare AI dashboard",
      createAccount: "Create Your NariCare Account",
      signupSub: "Join thousands of women managing their health with intelligent AI",
      email: "Email Address",
      password: "Password",
      name: "Full Name",
      age: "Age",
      phone: "Phone Number",
      rememberMe: "Remember me",
      agreeTerms: "I agree to NariCare Terms & Privacy Policy",
      alreadyAccount: "Already have an account? Login",
      needAccount: "Don't have an account? Sign Up"
    },
    onboarding: {
      welcome: "Set Up Your Healthcare Companion",
      step1Title: "Personal Profile",
      step2Title: "Health Preferences",
      step3Title: "Emergency & Language Settings",
      getStarted: "Get Started with NariCare"
    },
    permissionsPage: {
      title: "Permissions & Privacy Controls",
      subtitle: "Control location access, notifications, and microphone for voice assistant.",
      location: "Location Access (For nearby doctors)",
      notifications: "Push Notifications (For reminders)",
      microphone: "Microphone Access (For voice assistant)",
      allowAll: "Enable All Recommended Permissions",
      continue: "Continue to Dashboard"
    }
  },
  hi: {
    appName: "नारीकेयर AI",
    tagline: "आपका AI-संचालित महिला स्वास्थ्य साथी",
    heroDescription: "AI के माध्यम से महिलाओं को सुरक्षित, व्यक्तिगत और सुलभ स्वास्थ्य सेवा प्रदान करना।",
    login: "लॉग इन",
    signup: "साइन अप",
    learnMore: "और जानें",
    logout: "लॉग आउट",
    selectLanguage: "अपनी पसंदीदा भाषा चुनें",
    welcomeTitle: "नारीकेयर AI में आपका स्वागत है",
    welcomeSubtitle: "अपनी स्वास्थ्य यात्रा को अनुकूलित करने के लिए अपनी प्राथमिक भाषा चुनें।",
    navDashboard: "डैशबोर्ड",
    navNearby: "पास के डॉक्टर",
    navAINavigator: "AI नेविगेटर",
    navTimeline: "स्वास्थ्य रिकॉर्ड",
    navReminders: "रिमाइंडर",
    navMenstrual: "मासिक धर्म देखभाल",
    navPregnancy: "गर्भावस्था साथी",
    navEducation: "स्वास्थ्य शिक्षा",
    navProfile: "प्रोफ़ाइल और सेटिंग्स",
    goodMorning: "शुभ प्रभात",
    goodAfternoon: "शुभ दोपहर",
    goodEvening: "शुभ संध्या",
    todaysTip: "आज का महिला स्वास्थ्य टिप",
    nextReminder: "अगला दवा और पानी का रिमाइंडर",
    upcomingAppointment: "आगामी डॉक्टर अपॉइंटमेंट",
    currentCycle: "वर्तमान चक्र चरण",
    day: "दिन",
    follicular: "फॉलिक्युलर चरण",
    ovulation: "उर्वर खिड़की (Ovulation)",
    luteal: "ल्यूटीअल चरण",
    menstrual: "पीरियड चरण",
    landing: {
      promptBanner: "अपनी पसंदीदा भाषा चुनें:",
      currentlyIn: "वर्तमान भाषा",
      changeLang: "भाषा बदलें",
      heroBadge: "नेक्स्ट-जेन महिला स्वास्थ्य मंच",
      heroSub: "10 भारतीय भाषाओं, बुद्धिमान लक्षण चेकर और सत्यापित महिला डॉक्टरों के साथ भारत की महिलाओं के लिए विशेष रूप से डिज़ाइन किया गया।",
      goToDashboard: "डैशबोर्ड पर जाएं",
      safeConfidential: "सुरक्षित और गोपनीय",
      indianLanguages: "भारतीय भाषाएं",
      aiMedicalGuidance: "AI चिकित्सा मार्गदर्शन",
      verifiedFemaleDoctors: "सत्यापित महिला डॉक्टर",
      connectGynaecologists: "अपने पास के शीर्ष स्त्री रोग विशेषज्ञों से जुड़ें",
      careEngineTitle: "संपूर्ण देखभाल इंजन",
      careEngineHeading: "हर महिला के संपूर्ण स्वास्थ्य के लिए सब कुछ",
      careEngineSub: "मासिक चक्र ट्रैकिंग से लेकर आपातकालीन अस्पताल देखभाल और AI लक्षण निदान तक, नारीकेयर AI महिला जीवन के हर चरण के लिए निर्मित है।",
      exploreFeature: "सुविधा एक्सप्लोर करें",
      motherTongueTitle: "आपकी अपनी मातृभाषा में स्वास्थ्य सेवा",
      motherTongueSub: "कोई भाषा बाधा नहीं। अंग्रेजी, हिंदी, हिंग्लिश, बंगाली, मराठी, तेलुगु, तमिल, गुजराती, कन्नड़ या मलयालम में आसानी से नारीकेयर AI का उपयोग करें।"
    },
    featureCards: {
      aiNavTitle: "AI स्वास्थ्य नेविगेटर",
      aiNavDesc: "त्वरित लक्षण विश्लेषण, जोखिम ट्राइएज और व्यक्तिगत कार्य योजनाएं।",
      nearbyTitle: "पास की स्वास्थ्य सेवाएं",
      nearbyDesc: "सत्यापित महिला डॉक्टर खोजें, घर पर लैब टेस्ट और सुरक्षित परिवहन सेवाएं।",
      timelineTitle: "स्वास्थ्य टाइमलाइन",
      timelineSub: "डिजिटल स्वास्थ्य रिकॉर्ड, पुरानी लैब रिपोर्ट और AI निदान अंतर्दृष्टि।",
      remindersTitle: "स्मार्ट रिमाइंडर",
      remindersDesc: "दवाओं, पानी के सेवन, डॉक्टर विजिट और पीरियड ट्रैकिंग के लिए समय पर अलर्ट।",
      menstrualTitle: "मासिक धर्म देखभाल",
      menstrualDesc: "ओव्यूलेशन भविष्यवाणी, लक्षण लॉगिंग और पीरियड वेलनेस एनालिटिक्स।",
      pregnancyTitle: "गर्भावस्था साथी",
      pregnancyDesc: "सप्ताह-दर-सप्ताह गाइड, बम्प फोटो जर्नल और किक काउंटर।",
      educationTitle: "AI स्वास्थ्य शिक्षा",
      educationDesc: "शीर्ष महिला डॉक्टरों द्वारा तैयार किए गए लेख, मिथक-भंजक और वीडियो गाइड।"
    },
    cards: {
      nearby: "अपने पास स्वास्थ्य सेवा खोजें",
      nearbySub: "सत्यापित महिला डॉक्टर, घर पर लैब टेस्ट और परिवहन सेवा",
      aiNav: "AI स्वास्थ्य नेविगेटर",
      aiNavSub: "त्वरित लक्षण विश्लेषण, ट्राइएज और स्मार्ट सलाह",
      timeline: "स्वास्थ्य टाइमलाइन",
      timelineSub: "डिजिटल स्वास्थ्य रिकॉर्ड, नुस्खे और रिपोर्ट तिजोरी",
      reminders: "स्मार्ट रिमाइंडर",
      remindersSub: "दवा रिमाइंडर, अवधि ट्रैकर और जल स्तर",
      menstrual: "मासिक धर्म देखभाल",
      menstrualSub: "चक्र अंतर्दृष्टि, प्रजनन क्षमता और लक्षण लॉग",
      pregnancy: "गर्भावस्था साथी",
      pregnancySub: "सप्ताह-दर-सप्ताह गाइड, पेट की तस्वीरें और किक काउंटर",
      pregnancyDisabledMsg: "गर्भावस्था की योजना बना रही हैं या उम्मीद कर रही हैं?",
      enableButton: "साथी सक्षम करें",
      education: "AI स्वास्थ्य शिक्षा",
      educationSub: "बहुभाषी स्वास्थ्य लेख, मिथक-भंजक और पॉडकास्ट",
      profile: "प्रोफ़ाइल और सेटिंग्स",
      profileSub: "भाषा, अनुमतियां, आपातकालीन संपर्क और प्राथमिकताएं"
    },
    chatbot: {
      title: "नारी AI सहायक",
      subtitle: "महिला स्वास्थ्य, लक्षणों या उपचार के बारे में कुछ भी पूछें",
      placeholder: "नारी से अपने स्वास्थ्य के बारे में कुछ भी पूछें...",
      speaking: "नारी बोल रही है...",
      listening: "आपकी आवाज सुन रही है...",
      voiceInput: "बोलने के लिए टैप करें",
      stopVoice: "सुनना बंद करें",
      suggestedHeader: "सुझाए गए प्रश्न"
    },
    timeline: {
      title: "डिजिटल स्वास्थ्य रिकॉर्ड और टाइमलाइन",
      subtitle: "आपकी लैब रिपोर्ट, नुस्खों और AI विश्लेषण की सुरक्षित तिजोरी।",
      uploadButton: "स्वास्थ्य रिकॉर्ड अपलोड करें",
      sampleReports: "डेमो स्वास्थ्य रिकॉर्ड",
      viewReport: "देखें और विश्लेषण करें",
      aiAnalysis: "AI स्वास्थ्य विश्लेषण",
      allClear: "सामान्य सीमा",
      attentionNeeded: "डॉक्टर की सलाह आवश्यक",
      documentTitle: "दस्तावेज़ का शीर्षक",
      prescribingDoctor: "डॉक्टर / लैब",
      category: "श्रेणी",
      selectFile: "फ़ाइल चुनें",
      notesOptional: "रिपोर्ट परिणाम / नोट्स",
      uploading: "अपलोड हो रहा है...",
      cancel: "रद्द करें",
      saveVault: "तिजोरी में सहेजें"
    },
    menstrualPage: {
      title: "मासिक धर्म और प्रजनन ट्रैकर",
      subtitle: "चक्र चरणों का अनुमान लगाएं, लक्षणों को ट्रैक करें और AI मार्गदर्शन प्राप्त करें।",
      currentPhase: "वर्तमान चरण",
      fertileWindow: "उर्वर चरण (Fertile Window)",
      logSymptoms: "आज के लक्षण दर्ज करें",
      aiInsight: "नारी AI चक्र सारांश"
    },
    pregnancyPage: {
      title: "गर्भावस्था साथी और शिशु ट्रैकर",
      subtitle: "सप्ताह-दर-सप्ताह गाइड, किक काउंटर और व्यक्तिगत मातृ कल्याण सुझाव।",
      gestationalWeek: "गर्भावस्था का सप्ताह",
      dueDate: "अनुमानित प्रसव तिथि",
      kickCounter: "आज के किक काउंटर",
      weeklyGuide: "साप्ताहिक मील का पत्थर"
    },
    nearbyPage: {
      title: "पास के अस्पताल और टेलीकंसल्टेशन",
      subtitle: "शीर्ष महिला स्त्री रोग विशेषज्ञ, घर पर लैब टेस्ट और परिवहन खोजें।",
      filterFemaleDoctors: "केवल महिला डॉक्टर",
      homeDiagnostics: "घर पर सैंपल कलेक्शन उपलब्ध",
      transportAssistance: "अस्पताल परिवहन सेवा",
      bookAppointment: "अपॉइंटमेंट बुक करें",
      callEmergency: "हेल्पलाइन पर कॉल करें"
    },
    educationPage: {
      title: "AI स्वास्थ्य शिक्षा और ज्ञान भंडार",
      subtitle: "डॉक्टरों द्वारा सत्यापित स्वास्थ्य लेख, मिथक-भंजक और ऑडियो गाइड।",
      readArticle: "पूरा लेख पढ़ें",
      mythBusters: "मिथक बनाम तथ्य",
      podcasts: "पॉडकास्ट सुनें"
    },
    remindersPage: {
      title: "स्मार्ट दवा और हाइड्रेशन रिमाइंडर",
      subtitle: "अपनी दवाएं, पानी पीने का लक्ष्य या डॉक्टर अपॉइंटमेंट कभी न भूलें।",
      addReminder: "नया रिमाइंडर जोड़ें",
      pillAlert: "दवा का अलर्ट",
      hydrationAlert: "जल स्तर लक्ष्य",
      activeReminders: "सक्रिय रिमाइंडर"
    },
    profilePage: {
      title: "प्रोफ़ाइल और व्यक्तिगत सेटिंग्स",
      subtitle: "अपनी स्वास्थ्य प्राथमिकताओं, वैश्विक भाषा और अनुमतियों का प्रबंधन करें।",
      personalInfo: "व्यक्तिगत जानकारी",
      languagePref: "वैश्विक पसंदीदा भाषा",
      permissions: "ऐप और डिवाइस अनुमतियां",
      emergencyContacts: "आपातकालीन संपर्क नंबर",
      saveChanges: "प्राथमिकताएं सहेजें"
    },
    auth: {
      welcomeBack: "नारीकेयर में पुनः स्वागत है",
      signinSub: "अपने व्यक्तिगत नारीकेयर AI डैशबोर्ड तक पहुंचने के लिए साइन इन करें",
      createAccount: "अपना नारीकेयर खाता बनाएं",
      signupSub: "बुद्धिमान AI के साथ अपने स्वास्थ्य का प्रबंधन करने वाली हजारों महिलाओं से जुड़ें",
      email: "ईमेल पता",
      password: "पासवर्ड",
      name: "पूरा नाम",
      age: "उम्र",
      phone: "फोन नंबर",
      rememberMe: "मुझे याद रखें",
      agreeTerms: "मैं नारीकेयर की शर्तों और गोपनीयता नीति से सहमत हूं",
      alreadyAccount: "क्या आपके पास पहले से खाता है? लॉग इन करें",
      needAccount: "खाता नहीं है? साइन अप करें"
    },
    onboarding: {
      welcome: "अपना स्वास्थ्य साथी सेट करें",
      step1Title: "व्यक्तिगत प्रोफ़ाइल",
      step2Title: "स्वास्थ्य प्राथमिकताएं",
      step3Title: "आपातकालीन और भाषा सेटिंग्स",
      getStarted: "नारीकेयर शुरू करें"
    },
    permissionsPage: {
      title: "अनुमतियां और गोपनीयता नियंत्रण",
      subtitle: "पास के डॉक्टरों, रिमाइंडर और वॉइस असिस्टेंट के लिए अनुमतियां प्रबंधित करें।",
      location: "लोकेशन एक्सेस (पास के डॉक्टरों के लिए)",
      notifications: "पुश नोटिफिकेशन (रिमाइंडर के लिए)",
      microphone: "माइक एक्सेस (वॉइस असिस्टेंट के लिए)",
      allowAll: "सभी अनुमतियां सक्षम करें",
      continue: "डैशबोर्ड पर जाएं"
    }
  },
  hinglish: {
    appName: "NariCare AI",
    tagline: "Aapka AI-Powered Women's Healthcare Companion",
    heroDescription: "AI ke saath mahilaon ko safe, personalized aur accessible healthcare pradan karna.",
    login: "Login",
    signup: "Sign Up",
    learnMore: "Aur Janein",
    logout: "Logout",
    selectLanguage: "Apni Preferred Language Chunein",
    welcomeTitle: "NariCare AI mein Aapka Swagat Hai",
    welcomeSubtitle: "Apni healthcare journey ko personalize karne ke liye language select karein.",
    navDashboard: "Dashboard",
    navNearby: "Doctors Khojein",
    navAINavigator: "AI Navigator",
    navTimeline: "Health Records",
    navReminders: "Reminders",
    navMenstrual: "Period Care",
    navPregnancy: "Pregnancy Companion",
    navEducation: "Health Education",
    navProfile: "Profile & Settings",
    goodMorning: "Good Morning",
    goodAfternoon: "Good Afternoon",
    goodEvening: "Good Evening",
    todaysTip: "Aaj Ka Women's Health Tip",
    nextReminder: "Next Medicine & Hydration Alert",
    upcomingAppointment: "Upcoming Doctor Appointment",
    currentCycle: "Current Cycle Phase",
    day: "Day",
    follicular: "Follicular Phase",
    ovulation: "Fertile Window (Ovulation)",
    luteal: "Luteal Phase",
    menstrual: "Period Phase",
    landing: {
      promptBanner: "Apni preferred language select karein:",
      currentlyIn: "Currently in",
      changeLang: "Language Badlein",
      heroBadge: "Next-Gen Women's Healthcare Platform",
      heroSub: "India ki mahilaon ke liye 10 native languages, smart symptom checker aur verified female doctors ke saath special design kiya gaya hai.",
      goToDashboard: "Dashboard Par Janein",
      safeConfidential: "100% Safe & Confidential",
      indianLanguages: "10+ Indian Languages",
      aiMedicalGuidance: "24/7 AI Medical Guidance",
      verifiedFemaleDoctors: "Verified Female Doctors",
      connectGynaecologists: "Apne paas ke top gynecologists se connect karein",
      careEngineTitle: "Comprehensive Care Engine",
      careEngineHeading: "Har Mahila Ke Complete Health & Care Ke Liye Sab Kuch",
      careEngineSub: "Monthly period tracking se lekar emergency hospital care aur AI symptom diagnosis tak, NariCare AI har stage ke liye ready hai.",
      exploreFeature: "Feature Explore Karein",
      motherTongueTitle: "Apni Matrubhasha Mein Healthcare",
      motherTongueSub: "Koi language barrier nahi. English, Hindi, Hinglish, Bengali, Marathi, Telugu, Tamil, Gujarati, Kannada ya Malayalam mein NariCare AI use karein."
    },
    featureCards: {
      aiNavTitle: "AI Health Navigator",
      aiNavDesc: "Clinical-grade symptom analysis, instant risk triage & personalized action plans.",
      nearbyTitle: "Nearby Healthcare",
      nearbyDesc: "Find verified female doctors, book doorstep blood diagnostics & safe medical rides.",
      timelineTitle: "Health Timeline",
      timelineDesc: "Secure digital health records, past lab reports, and AI diagnostic insights.",
      remindersTitle: "Smart Reminders",
      remindersDesc: "Timely alerts for supplements, water intake, doctor visits & period tracking.",
      menstrualTitle: "Menstrual Care",
      menstrualDesc: "Ovulation forecasting, symptom logging, and period wellness analytics.",
      pregnancyTitle: "Pregnancy Companion",
      pregnancyDesc: "Week-by-week trimester guidance, bump photo journal, and kick counter.",
      educationTitle: "AI Health Education",
      educationDesc: "Bite-sized articles, myth busters & video guides curated by top female obstetricians."
    },
    cards: {
      nearby: "Apne Paas Healthcare Khojein",
      nearbySub: "Verified female doctors, home lab tests & transport assistance",
      aiNav: "AI Health Navigator",
      aiNavSub: "Instant symptom analysis, triage & smart recommendations",
      timeline: "Health Timeline",
      timelineSub: "Digital health records, prescriptions & lab vault",
      reminders: "Smart Reminders",
      remindersSub: "Medicine alerts, period tracker & hydration target",
      menstrual: "Menstrual Care",
      menstrualSub: "Cycle insights, fertility window & symptom logging",
      pregnancy: "Pregnancy Companion",
      pregnancySub: "Week-by-week guide, bump photos & kick counter",
      pregnancyDisabledMsg: "Pregnancy plan kar rahe hain ya expecting hain?",
      enableButton: "Enable Companion",
      education: "AI Health Education",
      educationSub: "Multilingual health articles, myth-busters & audio podcasts",
      profile: "Profile & Settings",
      profileSub: "Language, permissions, emergency contacts & preferences"
    },
    chatbot: {
      title: "Nari AI Assistant",
      subtitle: "Women's health, symptoms ya care ke baare mein kuch bhi poochein",
      placeholder: "Nari se apni health ke baare mein kuch bhi poochein...",
      speaking: "Nari bol rahi hai...",
      listening: "Aapki aawaz sun rahi hai...",
      voiceInput: "Tap Karke Bolein",
      stopVoice: "Listening Band Karein",
      suggestedHeader: "Suggested Questions"
    },
    timeline: {
      title: "Digital Health Records & Timeline",
      subtitle: "Aapke lab reports, prescriptions aur AI summary ki safe vault.",
      uploadButton: "Health Record Upload Karein",
      sampleReports: "Health Records",
      viewReport: "View & Interpret",
      aiAnalysis: "AI Health Analysis",
      allClear: "Normal Range",
      attentionNeeded: "Doctor Consultation Advised"
    },
    menstrualPage: {
      title: "Menstrual Cycle & Fertility Tracker",
      subtitle: "Cycle phases predict karein, symptoms log karein aur AI guidance payein.",
      currentPhase: "Current Phase",
      fertileWindow: "Fertile Window",
      logSymptoms: "Aaj Ke Symptoms Log Karein",
      aiInsight: "Nari AI Cycle Summary"
    },
    pregnancyPage: {
      title: "Pregnancy Companion & Fetal Tracker",
      subtitle: "Week-by-week guidance, kick tracking aur maternal wellness tips.",
      gestationalWeek: "Gestational Week",
      dueDate: "Estimated Due Date",
      kickCounter: "Aaj Ke Kicks Count",
      weeklyGuide: "Weekly Milestones"
    },
    nearbyPage: {
      title: "Nearby Healthcare & Teleconsultation",
      subtitle: "Top-rated female gynecologists, home sample collection & transport khojein.",
      filterFemaleDoctors: "Only Female Doctors",
      homeDiagnostics: "Home Sample Pickup Available",
      transportAssistance: "Hospital Transport Service",
      bookAppointment: "Appointment Book Karein",
      callEmergency: "Call Helpline"
    },
    educationPage: {
      title: "AI Health Education & Knowledge Vault",
      subtitle: "Doctor-verified health articles, myth-busters aur wellness audio guides.",
      readArticle: "Full Guide Padhein",
      mythBusters: "Myth vs Fact",
      podcasts: "Listen to Podcast"
    },
    remindersPage: {
      title: "Smart Medication & Hydration Reminders",
      subtitle: "Apni medicines, water goal ya doctor appointments kabhi na bhoolein.",
      addReminder: "New Reminder Add Karein",
      pillAlert: "Medicine Alert",
      hydrationAlert: "Hydration Target",
      activeReminders: "Active Reminders"
    },
    profilePage: {
      title: "Profile & Personal Settings",
      subtitle: "Apni health preferences, global language aur permissions manage karein.",
      personalInfo: "Personal Details",
      languagePref: "Global Preferred Language",
      permissions: "App & Device Permissions",
      emergencyContacts: "Emergency Contacts",
      saveChanges: "Preferences Save Karein"
    },
    auth: {
      welcomeBack: "NariCare Mein Phir Se Swagat Hai",
      signinSub: "Apne personalized NariCare AI dashboard par jane ke liye sign in karein",
      createAccount: "Apna NariCare Account Banayein",
      signupSub: "AI ke saath apni health manage karne wali hazaaron mahilaon se judein",
      email: "Email Address",
      password: "Password",
      name: "Full Name",
      age: "Age",
      phone: "Phone Number",
      rememberMe: "Mujhe yaad rakhein",
      agreeTerms: "Main NariCare Terms & Privacy Policy se agree karta/karti hoon",
      alreadyAccount: "Pehle se account hai? Login karein",
      needAccount: "Account nahi hai? Sign Up karein"
    },
    onboarding: {
      welcome: "Apna Healthcare Companion Set Karein",
      step1Title: "Personal Profile",
      step2Title: "Health Preferences",
      step3Title: "Emergency & Language Settings",
      getStarted: "NariCare Start Karein"
    },
    permissionsPage: {
      title: "Permissions & Privacy Controls",
      subtitle: "Nearby doctors, reminders aur voice assistant ke liye permissions control karein.",
      location: "Location Access (Doctors ke liye)",
      notifications: "Push Notifications (Reminders ke liye)",
      microphone: "Microphone Access (Voice assistant ke liye)",
      allowAll: "All Permissions Allow Karein",
      continue: "Dashboard Par Janein"
    }
  },
  bn: {
    appName: "নারীকেয়ার AI",
    tagline: "আপনার AI-চালित নারী স্বাস্থ্য সঙ্গী",
    heroDescription: "AI এর মাধ্যমে নারীদের জন্য নিরাপদ, ব্যক্তিগত এবং সহজলভ্য স্বাস্থ্যসেবা সুনিশ্চিত করা।",
    login: "লগইন",
    signup: "সাইন আপ",
    learnMore: "আরও জানুন",
    logout: "লগআউট",
    selectLanguage: "পছন্দের ভাষা নির্বাচন করুন",
    welcomeTitle: "নারীকেয়ার AI-তে স্বাগতম",
    welcomeSubtitle: "আপনার স্বাস্থ্য যাত্রা ব্যক্তিকৃত করতে প্রাথমিক ভাষা নির্বাচন করুন।",
    navDashboard: "ড্যাশবোর্ড",
    navNearby: "নিকটস্থ ডাক্তার",
    navAINavigator: "AI নেভিগেটর",
    navTimeline: "স্বাস্থ্য রেকর্ডস",
    navReminders: "রিমাইন্ডার",
    navMenstrual: "মাসিক সেবা",
    navPregnancy: "গর্ভাবস্থা সঙ্গী",
    navEducation: "স্বাস্থ্য শিক্ষা",
    navProfile: "প্রোফাইল ও সেটিংস",
    goodMorning: "সুপ্রভাত",
    goodAfternoon: "শুভ অপরাহ্ন",
    goodEvening: "শুভ সন্ধ্যা",
    todaysTip: "আজকের নারী স্বাস্থ্য টিপস",
    nextReminder: "পরবর্তী ওষুধ ও জল পানের রিমাইন্ডার",
    upcomingAppointment: "আসন্ন ডাক্তার অ্যাপয়েন্টমেন্ট",
    currentCycle: "বর্তমান চক্রের পর্যায়",
    day: "দিন",
    follicular: "ফলিকুলার পর্যায়",
    ovulation: "ডিম্বস্ফোটন পর্যায় (Ovulation)",
    luteal: "লিউটিয়াল পর্যায়",
    menstrual: "মাসিক পর্যায়",
    landing: {
      promptBanner: "আপনার পছন্দের ভাষা নির্বাচন করুন:",
      currentlyIn: "বর্তমান ভাষা",
      changeLang: "ভাষা পরিবর্তন করুন",
      heroBadge: "পরবর্তী প্রজন্মের নারী স্বাস্থ্য প্ল্যাটফর্ম",
      heroSub: "১০টি ভারতীয় ভাষা এবং এআই প্রযুক্তি সহ নারীদের স্বাস্থ্যের পূর্ণাঙ্গ সমাধান।",
      goToDashboard: "ড্যাশবোর্ডে যান",
      safeConfidential: "নিরাপদ ও গোপনীয়",
      indianLanguages: "ভারতীয় ভাষাসমূহ",
      aiMedicalGuidance: "AI চিকিৎসা দিকনির্দেশনা",
      verifiedFemaleDoctors: "যাচাইকৃত মহিলা ডাক্তার",
      connectGynaecologists: "নিকটস্থ স্ত্রী রোগ বিশেষজ্ঞদের সাথে যোগাযোগ করুন",
      careEngineTitle: "সম্পূর্ণ স্বাস্থ্য কেয়ার ইঞ্জিন",
      careEngineHeading: "প্রতিটি নারীর সম্পূর্ণ স্বাস্থ্যের প্রয়োজনীয় সবকিছু",
      careEngineSub: "মাসিক চক্র ট্র্যাকিং থেকে শুরু করে জরুরি চিকিৎসা পর্যন্ত নারীর জীবনের প্রতিটি ধাপে আমরা পাশে আছি।",
      exploreFeature: "ফিচার দেখুন",
      motherTongueTitle: "আপনার মাতৃভাষায় স্বাস্থ্যসেবা",
      motherTongueSub: "কোনো ভাষার বাধা নেই। বাংলা, ইংরেজি, হিন্দি এবং অন্যান্য ভাষায় সহজেই ব্যবহার করুন।"
    },
    featureCards: {
      aiNavTitle: "AI স্বাস্থ্য নেভিগেটর",
      aiNavDesc: "দ্রুত লক্ষণ বিশ্লেষণ ও স্মার্ট স্বাস্থ্য পরামর্শ।",
      nearbyTitle: "কাছাকাছি স্বাস্থ্যসেবা",
      nearbyDesc: "মহিলা ডাক্তার ও ল্যাব টেস্টের সুবিধা।",
      timelineTitle: "স্বাস্থ্য টাইমলাইন",
      timelineDesc: "ডিজিটাল স্বাস্থ্য রেকর্ডস ও রিপোর্ট সংরক্ষণের নিরাপদ ভল্ট।",
      remindersTitle: "স্মার্ট রিমাইন্ডার",
      remindersDesc: "ওষুধ ও জল পানের নিয়মিত অ্যালার্ট।",
      menstrualTitle: "মাসিক সেবা",
      menstrualDesc: "পিরিয়ড ট্র্যাকিং ও উর্বরতার পূর্বাভাস।",
      pregnancyTitle: "গর্ভাবস্থা সঙ্গী",
      pregnancyDesc: "সপ্তাহভিত্তিক নির্দেশিকা ও কিক কাউন্টার।",
      educationTitle: "AI স্বাস্থ্য শিক্ষা",
      educationDesc: "স্বাস্থ্য নিবন্ধ ও অডিও গাইড।"
    },
    cards: {
      nearby: "কাছাকাছি স্বাস্থ্যসেবা খুঁজুন",
      nearbySub: "যাচাইকৃত মহিলা ডাক্তার, বাড়িতে ল্যাব টেস্ট এবং পরিবহন ব্যবস্থা",
      aiNav: "AI স্বাস্থ্য নেভিগেটর",
      aiNavSub: "দ্রুত লক্ষণ বিশ্লেষণ ও স্মার্ট পরামর্শ",
      timeline: "স্বাস্থ্য টাইমলাইন",
      timelineSub: "ডিজিটাল স্বাস্থ্য রেকর্ডস ও ল্যাব রিপোর্ট ভল্ট",
      reminders: "স্মার্ট রিমাইন্ডার",
      remindersSub: "ওষুধের অ্যালার্ট, পিরিয়ড ট্র্যাকার ও জল পানের লক্ষ্য",
      menstrual: "মাসিক সেবা",
      menstrualSub: "চক্রের তথ্য, প্রজনন ক্ষমতা ও লক্ষণ লগিং",
      pregnancy: "গর্ভাবস্থা সঙ্গী",
      pregnancySub: "সপ্তাহভিত্তিক নির্দেশিকা ও কিক কাউন্টার",
      pregnancyDisabledMsg: "গর্ভাবস্থার পরিকল্পনা করছেন?",
      enableButton: "চালু করুন",
      education: "AI স্বাস্থ্য শিক্ষা",
      educationSub: "বহুভাষিক স্বাস্থ্য নিবন্ধ ও পডকাস্ট",
      profile: "প্রোফাইল ও সেটিংস",
      profileSub: "ভাষা, অনুমতি ও জরুরি যোগাযোগ"
    },
    chatbot: {
      title: "নারী AI সহকারী",
      subtitle: "নারী স্বাস্থ্য, লক্ষণ বা প্রতিকার সম্পর্কে যেকোনো প্রশ্ন করুন",
      placeholder: "আপনার স্বাস্থ্য সম্পর্কে নারী-কে যা খুশি জিজ্ঞাসা করুন...",
      speaking: "নারী উত্তর দিচ্ছে...",
      listening: "আপনার কথা শুনছে...",
      voiceInput: "বলতে ট্যাপ করুন",
      stopVoice: "শোনা বন্ধ করুন",
      suggestedHeader: "পরামর্শমূলক প্রশ্নাবলী"
    }
  },
  mr: {
    appName: "नारीकेअर AI",
    tagline: "तुमचा AI-संचालित महिला आरोग्य साथी",
    heroDescription: "AI द्वारे महिलांना सुरक्षित, वैयक्तिक आणि सुलभ आरोग्य सेवा प्रदान करणे.",
    login: "लॉग इन",
    signup: "साइन अप",
    learnMore: "अधिक जाणून घ्या",
    logout: "लॉग आउट",
    selectLanguage: "तुमची आवडती भाषा निवडा",
    welcomeTitle: "नारीकेअर AI मध्ये तुमचे स्वागत आहे",
    welcomeSubtitle: "तुमचा आरोग्य प्रवास वैयक्तिकृत करण्यासाठी तुमची प्राथमिक भाषा निवडा.",
    navDashboard: "डॅशबोर्ड",
    navNearby: "जवळचे डॉक्टर",
    navAINavigator: "AI नॅव्हिगेटर",
    navTimeline: "आरोग्य नोंदी",
    navReminders: "रिमाइंडर्स",
    navMenstrual: "मासिक पाळी काळजी",
    navPregnancy: "गरोदरपण साथी",
    navEducation: "आरोग्य शिक्षण",
    navProfile: "प्रोफाइल आणि सेटिंग्ज",
    goodMorning: "शुभ प्रभात",
    goodAfternoon: "शुभ दुपार",
    goodEvening: "शुभ संध्याकाळ",
    todaysTip: "आजची महिला आरोग्य टीप",
    nextReminder: "पुढील औषध आणि पाणी रिमाइंडर",
    upcomingAppointment: "पुढील डॉक्टर अपॉइंटमेंट",
    currentCycle: "सध्याचा टप्पा",
    day: "दिवस",
    follicular: "फॉलिक्युलर टप्पा",
    ovulation: "ओव्हुलेशन टप्पा",
    luteal: "ल्यूटीअल टप्पा",
    menstrual: "मासिक पाळी टप्पा",
    landing: {
      promptBanner: "तुमची आवडती भाषा निवडा:",
      currentlyIn: "सध्याची भाषा",
      changeLang: "भाषा बदला",
      heroBadge: "नेक्स्ट-जेन महिला आरोग्य मंच",
      heroSub: "10 भारतीय भाषा, लक्षण तपासणी आणि विश्वसनीय महिला डॉक्टरांसह भारतीय महिलांसाठी विशेष डिझाइन केलेले.",
      goToDashboard: "डॅशबोर्डवर जा",
      safeConfidential: "सुरक्षित आणि गोपनीय",
      indianLanguages: "भारतीय भाषा",
      aiMedicalGuidance: "AI वैद्यकीय मार्गदर्शन",
      verifiedFemaleDoctors: "सत्यापित महिला डॉक्टर",
      connectGynaecologists: "जवळच्या तज्ज्ञ महिला डॉक्टरांशी संपर्क साधा",
      careEngineTitle: "संपूर्ण काळजी इंजिन",
      careEngineHeading: "प्रत्येक महिलेच्या आरोग्यासाठी सर्व काही",
      careEngineSub: "मासिक पाळी ट्रॅकिंगपासून आपत्कालीन उपचारांपर्यंत सर्व टप्प्यांवर मदत.",
      exploreFeature: "वैशिष्ट्य पहा",
      motherTongueTitle: "तुमच्या मातृभाषेत आरोग्य सेवा",
      motherTongueSub: "मराठी, हिंदी, इंग्रजी आणि इतर भाषांमध्ये सहज वापरा."
    },
    featureCards: {
      aiNavTitle: "AI आरोग्य नॅव्हिगेटर",
      aiNavDesc: "लक्षण विश्लेषण आणि त्वरित सल्ला.",
      nearbyTitle: "जवळचे डॉक्टर",
      nearbyDesc: "महिला डॉक्टर आणि लॅब चाचण्या.",
      timelineTitle: "आरोग्य नोंदी",
      timelineDesc: "डिजिटल आरोग्य नोंदी आणि रिपोर्ट तिजोरी.",
      remindersTitle: "स्मार्ट रिमाइंडर्स",
      remindersDesc: "औषधे आणि पाण्याचे रिमाइंडर.",
      menstrualTitle: "मासिक पाळी काळजी",
      menstrualDesc: "मासिक पाळी ट्रॅकिंग आणि सल्ला.",
      pregnancyTitle: "गरोदरपण साथी",
      pregnancyDesc: "आठवड्यानुसार गरोदरपण मार्गदर्शक.",
      educationTitle: "AI आरोग्य शिक्षण",
      educationDesc: "आरोग्य लेख आणि ऑडिओ मार्गदर्शक."
    },
    cards: {
      nearby: "जवळची आरोग्य सेवा शोधा",
      nearbySub: "महिला डॉक्टर, घरी लॅब टेस्ट आणि वाहतूक",
      aiNav: "AI आरोग्य नॅव्हिगेटर",
      aiNavSub: "लक्षण विश्लेषण आणि सल्ला",
      timeline: "आरोग्य टाइमलाइन",
      timelineSub: "डिजिटल आरोग्य नोंदी",
      reminders: "स्मार्ट रिमाइंडर्स",
      remindersSub: "औषध आणि पाणी रिमाइंडर",
      menstrual: "मासिक पाळी काळजी",
      menstrualSub: "चक्र माहिती आणि लक्षणे",
      pregnancy: "गरोदरपण साथी",
      pregnancySub: "आठवड्यानुसार मार्गदर्शक",
      pregnancyDisabledMsg: "गरोदरपणाचे नियोजन करत आहात?",
      enableButton: "सुरू करा",
      education: "AI आरोग्य शिक्षण",
      educationSub: "बहुभाषिक आरोग्य लेख आणि व्हिडिओ",
      profile: "प्रोफाइल आणि सेटिंग्ज",
      profileSub: "भाषा आणि परवानग्या"
    },
    chatbot: {
      title: "नारी AI सहाय्यक",
      subtitle: "महिला आरोग्याबद्दल काहीही विचारा",
      placeholder: "नारीला काहीही विचारा...",
      speaking: "नारी बोलत आहे...",
      listening: "ऐकत आहे...",
      voiceInput: "बोलण्यासाठी टॅप करा",
      stopVoice: "थांबवा",
      suggestedHeader: "सुचवलेले प्रश्न"
    }
  },
  te: {
    appName: "నారీకేర్ AI",
    tagline: "మీ AI-ఆధారిత మహిళా ఆరోగ్య సహచరి",
    heroDescription: "AI ద్వారా మహిళలకు సురక్షితమైన, వ్యక్తిగత మరియు అందుబాటులో ఉండే ఆరోగ్య సంరక్షణను అందించడం.",
    login: "లాగిన్",
    signup: "సైన్ అప్",
    learnMore: "మరింత తెలుసుకోండి",
    logout: "లాగౌట్",
    selectLanguage: "మీ ప్రాధాన్య భాషను ఎంచుకోండి",
    welcomeTitle: "నారీకేర్ AI కి స్వాగతం",
    welcomeSubtitle: "మీ ఆరోగ్య ప్రయాణాన్ని వ్యక్తిగతీకరించడానికి మీ భాషను ఎంచుకోండి.",
    navDashboard: "డాష్‌బోర్డ్",
    navNearby: "సమీప వైద్యులు",
    navAINavigator: "AI నేవిగేటర్",
    navTimeline: "ఆరోగ్య రికార్డులు",
    navReminders: "రిమైండర్లు",
    navMenstrual: "రుతుక్రమ సంరక్షణ",
    navPregnancy: "గర్భధారణ సహచరి",
    navEducation: "ఆరోగ్య విద్య",
    navProfile: "ప్రొఫైల్ & సెట్టింగ్‌లు",
    goodMorning: "శుభోదయం",
    goodAfternoon: "శుభ మధ్యాహ్నం",
    goodEvening: "శుభ సాయంత్రం",
    todaysTip: "నేటి మహిళా ఆరోగ్య చిట్కా",
    nextReminder: "తదుపరి మందుల & నీటి అలర్ట్",
    upcomingAppointment: "రాబోయే డాక్టర్ అపాయింట్‌మెంట్",
    currentCycle: "ప్రస్తుత చక్ర దశ",
    day: "రోజు",
    follicular: "ఫాలికులర్ దశ",
    ovulation: "అండాల విడుదల దశ (Ovulation)",
    luteal: "ల్యూటియల్ దశ",
    menstrual: "పీరియడ్ దశ",
    landing: {
      promptBanner: "మీ భాషను ఎంచుకోండి:",
      currentlyIn: "ప్రస్తుత భాష",
      changeLang: "భాష మార్చండి",
      heroBadge: "మహిళా ఆరోగ్య వేదిక",
      heroSub: "10 భారతీయ భాషలతో మహిళల ఆరోగ్య సంరక్షణ కోసం ప్రత్యేకంగా రూపొందించబడింది.",
      goToDashboard: "డాష్‌బోర్డ్‌కి వెళ్లండి",
      safeConfidential: "సురక్షితం & గోప్యత",
      indianLanguages: "భారతీయ భాషలు",
      aiMedicalGuidance: "AI వైద్య సలహా",
      verifiedFemaleDoctors: "మహిళా వైద్యులు",
      connectGynaecologists: "సమీపంలోని స్త్రీల వైద్య నిపుణులను సంప్రదించండి",
      careEngineTitle: "సంపూర్ణ సంరక్షణ",
      careEngineHeading: "మహిళల ఆరోగ్యం కోసం ప్రతి సేవ",
      careEngineSub: "రుతుక్రమ నమోదు నుండి గర్భధారణ వరకు ప్రతి దశలో మీతో ఉంటుంది.",
      exploreFeature: "వివరాలు చూడండి",
      motherTongueTitle: "మీ మాతృభాషలో వైద్య సేవలు",
      motherTongueSub: "తెలుగు, ఇంగ్లీష్, హిందీ మరియు ఇతర భాషలలో సేవలు లభించును."
    },
    featureCards: {
      aiNavTitle: "AI హెల్త్ నేవిగేటర్",
      aiNavDesc: "లక్షణ విశ్లేషణ మరియు తక్షణ సలహాలు.",
      nearbyTitle: "సమీప వైద్యులు",
      nearbyDesc: "మహిళా వైద్యులు మరియు ల్యాబ్ పరీక్షలు.",
      timelineTitle: "హెల్త్ టైమ్‌లైన్",
      timelineDesc: "డిజిటల్ రికార్డుల భద్రత.",
      remindersTitle: "స్మార్ట్ రిమైండర్లు",
      remindersDesc: "మందుల అలర్ట్‌లు మరియు నీటి అలర్ట్‌లు.",
      menstrualTitle: "రుతుక్రమ సంరక్షణ",
      menstrualDesc: "పీరియడ్ ట్రాకింగ్ మరియు విశ్లేషణ.",
      pregnancyTitle: "గర్భధారణ సహచరి",
      pregnancyDesc: "వారం వారం గైడ్ మరియు కిక్ కౌంటర్.",
      educationTitle: "AI ఆరోగ్య విద్య",
      educationDesc: "వైద్య సమాచారం మరియు వ్యాసాలు."
    },
    cards: {
      nearby: "మీ సమీపంలో వైద్య సేవలను కనుగొనండి",
      nearbySub: "ధృవీకరించబడిన మహిళా వైద్యులు, ఇంటి వద్ద ల్యాబ్ పరీక్షలు",
      aiNav: "AI హెల్త్ నేవిగేటర్",
      aiNavSub: "తక్షణ లక్షణ విశ్లేషణ మరియు సలహాలు",
      timeline: "హెల్త్ టైమ్‌లైన్",
      timelineSub: "డిజిటల్ ఆరోగ్య రికార్డులు మరియు నివేదికలు",
      reminders: "స్మార్ట్ రిమైండర్లు",
      remindersSub: "మందుల అలర్ట్‌లు మరియు పీరియడ్ ట్రాకర్",
      menstrual: "రుతుక్రమ సంరక్షణ",
      menstrualSub: "చక్ర వివరాలు మరియు సంతానోత్పత్తి సమాచారం",
      pregnancy: "గర్భధారణ సహచరి",
      pregnancySub: "వారం వారం గైడ్ మరియు కిక్ కౌంటర్",
      pregnancyDisabledMsg: "గర్భధారణ ప్రణాళికలో ఉన్నారా?",
      enableButton: "సక్షన్ చేయండి",
      education: "AI ఆరోగ్య విద్య",
      educationSub: "బహుభాషా ఆరోగ్య వ్యాసాలు మరియు ఆడియో గైడ్‌లు",
      profile: "ప్రొఫైల్ & సెట్టింగ్‌లు",
      profileSub: "భాష, అనుమతులు మరియు ప్రాధాన్యతలు"
    },
    chatbot: {
      title: "నారీ AI సహాయకురాలు",
      subtitle: "మహిళల ఆరోగ్యం లేదా లక్షణాల గురించి ఏమైనా అడగండి",
      placeholder: "నారీని మీ ఆరోగ్యం గురించి ఏమైనా అడగండి...",
      speaking: "నారీ మాట్లాడుతోంది...",
      listening: "వింటోంది...",
      voiceInput: "మాట్లాడటానికి నొక్కండి",
      stopVoice: "ఆపండి",
      suggestedHeader: "సూచించబడిన ప్రశ్నలు"
    }
  },
  ta: {
    appName: "நாரிகேர் AI",
    tagline: "உங்கள் AI-இயங்கும் பெண்கள் சுகாதார துணை",
    heroDescription: "AI மூலம் பெண்களுக்கு பாதுகாப்பான, தனிப்பயனாக்கப்பட்ட மற்றும் அணுகக்கூடிய சுகாதார சேவையை வழங்குதல்.",
    login: "லாகின்",
    signup: "சைன் அப்",
    learnMore: "மேலும் அறிய",
    logout: "லாக்அவுட்",
    selectLanguage: "விருப்பமான மொழியைத் தேர்ந்தெடுக்கவும்",
    welcomeTitle: "நாரிகேர் AI-க்கு வரவேற்கிறோம்",
    welcomeSubtitle: "உங்கள் சுகாதார பயணத்தைத் தனிப்பயனாக்க மொழியைத் தேர்ந்தெடுக்கவும்.",
    navDashboard: "டாஷ்போர்டு",
    navNearby: "அருகிலுள்ள மருத்துவர்கள்",
    navAINavigator: "AI நேவிகேட்டர்",
    navTimeline: "சுகாதார பதிவுகள்",
    navReminders: "நினைவூட்டல்கள்",
    navMenstrual: "மாதவிடாய் பராமரிப்பு",
    navPregnancy: "கர்ப்ப கால துணை",
    navEducation: "சுகாதார கல்வி",
    navProfile: "சுயவிவரம் & அமைப்புகள்",
    goodMorning: "காலை வணக்கம்",
    goodAfternoon: "மதிய வணக்கம்",
    goodEvening: "மாலை வணக்கம்",
    todaysTip: "இன்றைய மகளிர் சுகாதார குறிப்பு",
    nextReminder: "அடுத்த மருந்து மற்றும் தண்ணீர் நினைவூட்டல்",
    upcomingAppointment: "அடுத்த மருத்துவர் சந்திப்பு",
    currentCycle: "தற்போதைய சுழற்சி நிலை",
    day: "நாள்",
    follicular: "போலிகுலார் நிலை",
    ovulation: "கருவுறுதல் காலம் (Ovulation)",
    luteal: "லூட்டல் நிலை",
    menstrual: "மாதவிடாய் நிலை",
    landing: {
      promptBanner: "உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்:",
      currentlyIn: "தற்போதைய மொழி",
      changeLang: "மொழியை மாற்று",
      heroBadge: "மகளிர் சுகாதார தளம்",
      heroSub: "10 இந்திய மொழிகளில் பெண்களுக்கான பிரத்யேக சுகாதார தளம்.",
      goToDashboard: "டாஷ்போர்டிற்கு செல்",
      safeConfidential: "பாதுகாப்பானது & ரகசியமானது",
      indianLanguages: "இந்திய மொழிகள்",
      aiMedicalGuidance: "AI மருத்துவ வழிகாட்டல்",
      verifiedFemaleDoctors: "பெண் மருத்துவர்கள்",
      connectGynaecologists: "அருகிலுள்ள சிறந்த பெண் மருத்துவர்களை தொடர்பு கொள்ளவும்",
      careEngineTitle: "முழுமையான பராமரிப்பு",
      careEngineHeading: "பெண்களின் முழு சுகாதாரத்திற்கான அனைத்தும்",
      careEngineSub: "மாதவிடாய் கண்காணிப்பு முதல் கர்ப்ப காலம் வரை அனைத்து நிலைகளிலும் துணை நிற்கும்.",
      exploreFeature: "மேலும் அறிக",
      motherTongueTitle: "உங்கள் தாய்மொழியில் மருத்துவம்",
      motherTongueSub: "தமிழ், ஆங்கிலம், இந்தி மற்றும் பிற மொழிகளில் பயன்படுத்தலாம்."
    },
    featureCards: {
      aiNavTitle: "AI சுகாதார நேவிகேட்டர்",
      aiNavDesc: "உடனடி அறிகுறி பகுப்பாய்வு.",
      nearbyTitle: "அருகிலுள்ள மருத்துவர்கள்",
      nearbyDesc: "பெண் மருத்துவர்கள் மற்றும் வீட்டு பரிசோதனை.",
      timelineTitle: "சுகாதார காலவரிசை",
      timelineDesc: "டிஜிட்டல் மருத்துவ பதிவுகள்.",
      remindersTitle: "ஸ்மார்ட் நினைவூட்டல்கள்",
      remindersDesc: "மருந்து மற்றும் தண்ணீர் நினைவூட்டல்கள்.",
      menstrualTitle: "மாதவிடாய் பராமரிப்பு",
      menstrualDesc: "சுழற்சி தகவல்கள்.",
      pregnancyTitle: "கர்ப்ப கால துணை",
      pregnancyDesc: "வாராந்திர வழிகாட்டி.",
      educationTitle: "AI சுகாதார கல்வி",
      educationDesc: "சுகாதார கட்டுரைகள்."
    },
    cards: {
      nearby: "அருகிலுள்ள சுகாதார சேவைகளை கண்டறியவும்",
      nearbySub: "சான்றளிக்கப்பட்ட பெண் மருத்துவர்கள், வீட்டில் பரிசோதனை",
      aiNav: "AI சுகாதார நேவிகேட்டர்",
      aiNavSub: "உடனடி அறிகுறி பகுப்பாய்வு மற்றும் ஆலோசனைகள்",
      timeline: "சுகாதார காலவரிசை",
      timelineSub: "டிஜிட்டல் மருத்துவ பதிவுகள் மற்றும் அறிக்கைகள்",
      reminders: "ஸ்மார்ட் நினைவூட்டல்கள்",
      remindersSub: "மருந்து நினைவூட்டல்கள் மற்றும் மாதவிடாய் டிராக்கர்",
      menstrual: "மாதவிடாய் பராமரிப்பு",
      menstrualSub: "சுழற்சி தகவல்கள் மற்றும் அறிகுறி பதிவு",
      pregnancy: "கர்ப்ப கால துணை",
      pregnancySub: "வாராந்திர வழிகாட்டி மற்றும் கிக் கவுண்டர்",
      pregnancyDisabledMsg: "கர்ப்பத்திற்கு திட்டமிடுகிறீர்களா?",
      enableButton: "செயல்படுத்துக",
      education: "AI சுகாதார கல்வி",
      educationSub: "பல்மொழி சுகாதார கட்டுரைகள் மற்றும் ஆடியோ",
      profile: "சுயவிவரம் & அமைப்புகள்",
      profileSub: "மொழி, அனுமதிகள் மற்றும் விருப்பங்கள்"
    },
    chatbot: {
      title: "நாரி AI உதவியாளர்",
      subtitle: "பெண்கள் ఆరోగ్యం பற்றி எதையும் கேளுங்கள்",
      placeholder: "நாரியிடம் எதையும் கேளுங்கள்...",
      speaking: "நாரி பேசுகிறார்...",
      listening: "கேட்கிறது...",
      voiceInput: "பேச தட்டவும்",
      stopVoice: "நிறுத்து",
      suggestedHeader: "பரிந்துரைக்கப்பட்ட கேள்விகள்"
    }
  },
  gu: {
    appName: "નારીકેર AI",
    tagline: "તમારું AI-સંચાલિત મહિલા હેલ્થકેર સાથી",
    heroDescription: "AI દ્વારા મહિલાઓને સુરક્ષિત, વ્યક્તિગત અને સુલભ આરોગ્ય સંભાળ પૂરી પાડવી.",
    login: "લોગ ઇન",
    signup: "સાઇન અપ",
    learnMore: "વધુ જાણો",
    logout: "લોગ આઉટ",
    selectLanguage: "તમારી પસંદગીની ભાષા પસંદ કરો",
    welcomeTitle: "નારીકેર AI માં આપનું સ્વાગત છે",
    welcomeSubtitle: "તમારી હેલ્થકેર યાત્રાને વ્યક્તિગત કરવા માટે પ્રાથમિક ભાષા પસંદ કરો.",
    navDashboard: "ડેશબોર્ડ",
    navNearby: "નજીકના ડોકટરો",
    navAINavigator: "AI નેવિગેટર",
    navTimeline: "હેલ્થ રેકોર્ડ્સ",
    navReminders: "રિમાઇન્ડર્સ",
    navMenstrual: "માસિક સંભાળ",
    navPregnancy: "ગર્ભાવસ્થા સાથી",
    navEducation: "આરોગ્ય શિક્ષણ",
    navProfile: "પ્રોફાઇલ અને સેટિંગ્સ",
    goodMorning: "સુપ્રભાત",
    goodAfternoon: "શુભ બપોર",
    goodEvening: "શુભ સાંજ",
    todaysTip: "આજની મહિલા આરોગ્ય ટિપ",
    nextReminder: "આગામી દવા અને પાણીનું રિમાઇન્ડર",
    upcomingAppointment: "આગામી ડોક્ટર એપોઇન્ટમેન્ટ",
    currentCycle: "વર્તમાન તબક્કો",
    day: "દિવસ",
    follicular: "ફોલિક્યુલર તબક્કો",
    ovulation: "ઓવ્યુલેશન તબક્કો",
    luteal: "લ્યુટીયલ તબક્કો",
    menstrual: "પીરિયડ તબક્કો",
    landing: {
      promptBanner: "તમારી પસંદગીની ભાષા પસંદ કરો:",
      currentlyIn: "વર્તમાન ભાષા",
      changeLang: "ભાષા બદલો",
      heroBadge: "મહિલા હેલ્થકેર પ્લેટફોર્મ",
      heroSub: "10 ભારતીય ભાષાઓ અને AI ટેકનોલોજી સાથે મહિલાઓના સ્વાસ્થ્ય માટે વિશેષ નિર્મિત.",
      goToDashboard: "ડેશબોર્ડ પર જાઓ",
      safeConfidential: "સુરક્ષિત અને ગોપનીય",
      indianLanguages: "ભારતીય ભાષાઓ",
      aiMedicalGuidance: "AI તબીબી માર્ગદર્શન",
      verifiedFemaleDoctors: "ચકાસાયેલ મહિલા ડોકટરો",
      connectGynaecologists: "નજીકના શ્રેષ્ઠ મહિલા ડોકટરો સાથે જોડાઓ",
      careEngineTitle: "સંપૂર્ણ સંભાળ એન્જિન",
      careEngineHeading: "મહિલા સ્વાસ્થ્ય માટે જરૂરી બધું જ",
      careEngineSub: "માસિક ચક્ર ટ્રેકિંગથી લઈને ગર્ભાવસ્થા સુધીની તમામ માહિતી.",
      exploreFeature: "વધુ જાણો",
      motherTongueTitle: "તમારી પોતાની માતૃભાષામાં આરોગ્ય સંભાળ",
      motherTongueSub: "ગુજરાતી, હિન્દી, અંગ્રેજી અને અન્ય ભાષાઓમાં વાપરો."
    },
    featureCards: {
      aiNavTitle: "AI હેલ્થ નેવિગેટર",
      aiNavDesc: "ઝડપી લક્ષણ વિશ્લેષણ અને સલાહ.",
      nearbyTitle: "નજીકના ડોકટરો",
      nearbyDesc: "મહિલા ડોકટરો અને લૅબ ચકાસણી.",
      timelineTitle: "હેલ્થ ટાઇમલાઇન",
      timelineDesc: "ડિજિટલ હેલ્થ રેકોર્ડ્સ.",
      remindersTitle: "સ્માર્ટ રિમાઇન્ડર્સ",
      remindersDesc: "દવા અને પાણીનું રિમાઇન્ડર.",
      menstrualTitle: "માસિક સંભાળ",
      menstrualDesc: "સાયકલ ઇનસાઇટ્સ.",
      pregnancyTitle: "ગર્ભાવસ્થા સાથી",
      pregnancyDesc: "અઠવાડિયા મુજબ ગાઇડ.",
      educationTitle: "AI આરોગ્ય શિક્ષણ",
      educationDesc: "આરોગ્ય લેખો અને પોડકાસ્ટ."
    },
    cards: {
      nearby: "તમારી નજીક આરોગ્ય સંભાળ શોધો",
      nearbySub: "ચકાસાયેલ મહિલા ડોકટરો, ઘરે લૅબ ટેસ્ટ અને પરિવહન",
      aiNav: "AI હેલ્થ નેવિગેટર",
      aiNavSub: "ઝડપી લક્ષણ વિશ્લેષણ અને સ્માર્ટ સલાહ",
      timeline: "હેલ્થ ટાઇમલાઇન",
      timelineSub: "ડિજિટલ હેલ્થ રેકોર્ડ્સ અને રિપોર્ટ્સ",
      reminders: "સ્માર્ટ રિમાઇન્ડર્સ",
      remindersSub: "દવા રિમાઇન્ડર્સ અને વોટર ટાર્ગેટ",
      menstrual: "માસિક સંભાળ",
      menstrualSub: "સાયકલ ઇનસાઇટ્સ અને ફર્ટિલિટી વિન્ડો",
      pregnancy: "ગર્ભાવસ્થા સાથી",
      pregnancySub: "અઠવાડિયા મુજબ ગાઇડ અને કિક કાઉન્ટર",
      pregnancyDisabledMsg: "ગર્ભાવસ્થાનું આયોજન કરી રહ્યા છો?",
      enableButton: "ચાલુ કરો",
      education: "AI આરોગ્ય શિક્ષણ",
      educationSub: "બહુભાષી આરોગ્ય લેખો અને પોડકાસ્ટ",
      profile: "પ્રોફાઇલ અને સેટિંગ્સ",
      profileSub: "ભાષા, પરવાનગીઓ અને પ્રાથમિકતાઓ"
    },
    chatbot: {
      title: "નારી AI સહાયક",
      subtitle: "મહિલા આરોગ્ય વિશે કંઈપણ પૂછો",
      placeholder: "નારીને કંઈપણ પૂછો...",
      speaking: "નારી બોલી રહી છે...",
      listening: "સાંભળી રહી છે...",
      voiceInput: "બોલવા માટે ટેપ કરો",
      stopVoice: "બંધ કરો",
      suggestedHeader: "સૂચવેલા પ્રશ્નો"
    }
  },
  kn: {
    appName: "ನಾರಿಕೇರ್ AI",
    tagline: "ನಿಮ್ಮ AI-ಚಾಲಿತ ಮಹಿಳಾ ಆರೋಗ್ಯ ಸಂಗಾತಿ",
    heroDescription: "AI ಮೂಲಕ ಮಹಿಳೆಯರಿಗೆ ಸುರಕ್ಷಿತ, ವೈಯಕ್ತಿಕ ಮತ್ತು ಸುಲಭವಾಗಿ ಲಭ್ಯವಿರುವ ಆರೋಗ್ಯ ಸೇವೆಯನ್ನು ಒದಗಿಸುವುದು.",
    login: "ಲಾಗಿನ್",
    signup: "ಸೈನ್ ಅಪ್",
    learnMore: "ಮತ್ತಷ್ಟು ತಿಳಿಯಿರಿ",
    logout: "ಲಾಗೌಟ್",
    selectLanguage: "ನಿಮ್ಮ ಆಯ್ಕೆಯ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    welcomeTitle: "ನಾರಿಕೇರ್ AI ಗೆ ಸ್ವಾಗತ",
    welcomeSubtitle: "ನಿಮ್ಮ ಆರೋಗ್ಯ ಪ್ರಯಾಣವನ್ನು ವೈಯಕ್ತೀಕರಿಸಲು ನಿಮ್ಮ ಪ್ರಾಥಮಿಕ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ.",
    navDashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    navNearby: "ಹತ್ತಿರದ ವೈದ್ಯರು",
    navAINavigator: "AI ನ್ಯಾವಿಗೇಟರ್",
    navTimeline: "ಆರೋಗ್ಯ ದಾಖಲೆಗಳು",
    navReminders: "ಜ್ಞಾಪನೆಗಳು",
    navMenstrual: "ಋತುಚಕ್ರದ ಆರೈಕೆ",
    navPregnancy: "ಗರ್ಭಧಾರಣೆ ಸಂಗಾತಿ",
    navEducation: "ಆರೋಗ್ಯ ಶಿಕ್ಷಣ",
    navProfile: "ಪ್ರೊಫೈಲ್ ಮತ್ತು ಸಂಯೋಜನೆಗಳು",
    goodMorning: "ಶುಭೋದಯ",
    goodAfternoon: "ಶುಭ ಮಧ್ಯಾಹ್ನ",
    goodEvening: "ಶುಭ ಸಂಜೆ",
    todaysTip: "ಇಂದಿನ ಮಹಿಳಾ ಆರೋಗ್ಯ ಸಲಹೆ",
    nextReminder: "ಮುಂದಿನ ಔಷಧ ಮತ್ತು ನೀರು ಕುಡಿಯುವ ಜ್ಞಾಪನೆ",
    upcomingAppointment: "ಮುಂದಿನ ವೈದ್ಯರ ಭೇಟಿ",
    currentCycle: "ಪ್ರಸ್ತುತ ಹಂತ",
    day: "ದಿನ",
    follicular: "ಫೋಲಿಕ್ಯುಲರ್ ಹಂತ",
    ovulation: "ಅಂಡೋತ್ಪತ್ತಿ ಹಂತ (Ovulation)",
    luteal: "ಲ್ಯೂಟಿಯಲ್ ಹಂತ",
    menstrual: "ಋತುಚಕ್ರದ ಹಂತ",
    landing: {
      promptBanner: "ನಿಮ್ಮ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ:",
      currentlyIn: "ಪ್ರಸ್ತುತ ಭಾಷೆ",
      changeLang: "ಭಾಷೆ ಬದಲಾಯಿಸಿ",
      heroBadge: "ಮಹಿಳಾ ಆರೋಗ್ಯ ವೇದಿಕೆ",
      heroSub: "10 ಭಾರತೀಯ ಭಾಷೆಗಳಲ್ಲಿ ಮಹಿಳೆಯರ ಆರೋಗ್ಯಕ್ಕಾಗಿ ವಿಶೇಷವಾಗಿ ವಿನ್ಯಾಸಗೊಳಿಸಲಾಗಿದೆ.",
      goToDashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗೆ ಹೋಗಿ",
      safeConfidential: "ಸುರಕ್ಷಿತ ಮತ್ತು ಗೌಪ್ಯ",
      indianLanguages: "ಭಾರತೀಯ ಭಾಷೆಗಳು",
      aiMedicalGuidance: "AI ವೈದ್ಯಕೀಯ ಮಾರ್ಗದರ್ಶನ",
      verifiedFemaleDoctors: "ಮಹಿಳಾ ವೈದ್ಯರು",
      connectGynaecologists: "ನಿಮ್ಮ ಹತ್ತಿರದ ವೈದ್ಯರೊಂದಿಗೆ ಸಂಪರ್ಕ ಸಾಧಿಸಿ",
      careEngineTitle: "ಸಂಪೂರ್ಣ ಆರೈಕೆ",
      careEngineHeading: "ಮಹಿಳೆಯರ ಆರೋಗ್ಯಕ್ಕೆ ಅಗತ್ಯವಿರುವ ಪ್ರತಿಯೊಂದೂ",
      careEngineSub: "ಋತುಚಕ್ರದಿಂದ ಗರ್ಭಧಾರಣೆಯವರೆಗೆ ಪ್ರತಿಯೊಂದು ಹಂತದಲ್ಲೂ ನಿಮಗಾಗಿ ಜತೆಗಿರುತ್ತದೆ.",
      exploreFeature: "ಮತ್ತಷ್ಟು ತಿಳಿಯಿರಿ",
      motherTongueTitle: "ನಿಮ್ಮ ಮಾತೃಭಾಷೆಯಲ್ಲಿ ಆರೋಗ್ಯ ಸೇವೆ",
      motherTongueSub: "ಕನ್ನಡ, ಇಂಗ್ಲಿಷ್, ಹಿಂದಿ ಮತ್ತು ಇತರ ಭಾಷೆಗಳಲ್ಲಿ ಬಳಸಿ."
    },
    featureCards: {
      aiNavTitle: "AI ಆರೋಗ್ಯ ನ್ಯಾವಿಗೇಟರ್",
      aiNavDesc: "ರೋಗಲಕ್ಷಣ ವಿಶ್ಲೇಷಣೆ ಮತ್ತು ತಕ್ಷಣದ ಸಲಹೆಗಳು.",
      nearbyTitle: "ಹತ್ತಿರದ ವೈದ್ಯರು",
      nearbyDesc: "ಮಹಿಳಾ ವೈದ್ಯರು ಮತ್ತು ಲ್ಯಾಬ್ ಪರೀಕ್ಷೆಗಳು.",
      timelineTitle: "ಆರೋಗ್ಯ ಟೈಮ್‌ಲೈನ್",
      timelineDesc: "ಡಿಜಿಟಲ್ ಆರೋಗ್ಯ ದಾಖಲೆಗಳು.",
      remindersTitle: "ಸ್ಮಾರ್ಟ್ ಜ್ಞಾಪನೆಗಳು",
      remindersDesc: "ಔಷಧ ಮತ್ತು ನೀರಿನ ಜ್ಞಾಪನೆಗಳು.",
      menstrualTitle: "ಋತುಚಕ್ರದ ಆರೈಕೆ",
      menstrualDesc: "ಋತುಚಕ್ರದ ಮಾಹಿತಿ.",
      pregnancyTitle: "ಗರ್ಭಧಾರಣೆ ಸಂಗಾತಿ",
      pregnancyDesc: "ವಾರದ ಮಾರ್ಗದರ್ಶಿ.",
      educationTitle: "AI ಆರೋಗ್ಯ ಶಿಕ್ಷಣ",
      educationDesc: "ಆರೋಗ್ಯ ಲೇಖನಗಳು."
    },
    cards: {
      nearby: "ನಿಮ್ಮ ಹತ್ತಿರದ ಆರೋಗ್ಯ ಸೇವೆಯನ್ನು ಹುಡುಕಿ",
      nearbySub: "ಮಹಿಳಾ ವೈದ್ಯರು, ಮನೆಬಾಗಿಲಿನಲ್ಲಿ ಲ್ಯಾಬ್ ಪರೀಕ್ಷೆಗಳು",
      aiNav: "AI ಆರೋಗ್ಯ ನ್ಯಾವಿಗೇಟರ್",
      aiNavSub: "ತಕ್ಷಣದ ರೋಗಲಕ್ಷಣ ವಿಶ್ಲೇಷಣೆ ಮತ್ತು ಸಲಹೆಗಳು",
      timeline: "ಆರೋಗ್ಯ ಟೈಮ್‌ಲೈನ್",
      timelineSub: "ಡಿಜಿಟಲ್ ಆರೋಗ್ಯ ದಾಖಲೆಗಳು ಮತ್ತು ವರದಿಗಳು",
      reminders: "ಸ್ಮಾರ್ಟ್ ಜ್ಞಾಪನೆಗಳು",
      remindersSub: "ಔಷಧ ಜ್ಞಾಪನೆಗಳು ಮತ್ತು ಋತುಚಕ್ರ ಟ್ರ್ಯಾಕರ್",
      menstrual: "ಋತುಚಕ್ರದ ಆರೈಕೆ",
      menstrualSub: "ಋತುಚಕ್ರದ ವಿವರಗಳು ಮತ್ತು ಫಲವತ್ತತೆ ಮಾಹಿತಿ",
      pregnancy: "ಗರ್ಭಧಾರಣೆ ಸಂಗಾತಿ",
      pregnancySub: "ವಾರದ ಮಾರ್ಗದರ್ಶಿ ಮತ್ತು ಕಿಕ್ ಕೌಂಟರ್",
      pregnancyDisabledMsg: "ಗರ್ಭಧಾರಣೆಯ ಯೋಜನೆ ಮಾಡುತ್ತಿದ್ದೀರಾ?",
      enableButton: "ಸಕ್ರಿಯಗೊಳಿಸಿ",
      education: "AI ಆರೋಗ್ಯ ಶಿಕ್ಷಣ",
      educationSub: "ಬಹುಭಾಷಾ ಆರೋಗ್ಯ ಲೇಖನಗಳು ಮತ್ತು ಆಡಿಯೋ",
      profile: "ಪ್ರೊಫೈಲ್ ಮತ್ತು ಸಂಯೋಜನೆಗಳು",
      profileSub: "ಭಾಷೆ, ಅನುಮತಿಗಳು ಮತ್ತು ಆದ್ಯತೆಗಳು"
    },
    chatbot: {
      title: "ನಾರಿ AI ಸಹಾಯಕ",
      subtitle: "ಮಹಿಳೆಯರ ಆರೋಗ್ಯದ ಬಗ್ಗೆ ಏನನ್ನಾದರೂ ಕೇಳಿ",
      placeholder: "ನಾರಿಯನ್ನು ಕೇಳಿ...",
      speaking: "ನಾರಿ ಮಾತನಾಡುತ್ತಿದ್ದಾಳೆ...",
      listening: "ಆಲಿಸುತ್ತಿದೆ...",
      voiceInput: "ಮಾತನಾಡಲು ಟ್ಯಾಪ್ ಮಾಡಿ",
      stopVoice: "ನಿಲ್ಲಿಸಿ",
      suggestedHeader: "ಸೂಚಿಸಲಾದ ಪ್ರಶ್ನೆಗಳು"
    }
  },
  ml: {
    appName: "നാരിെയർ AI",
    tagline: "നിങ്ങളുടെ AI-അധിഷ്ഠിത വനിതാ ആരോഗ്യ സഹായി",
    heroDescription: "AI വഴി സ്ത്രീകൾക്ക് സുരക്ഷിതവും വ്യക്തിഗതവുമായ ആരോഗ്യ സേവനങ്ങൾ ഉറപ്പാക്കുന്നു.",
    login: "ലോഗിൻ",
    signup: "സൈൻ അപ്പ്",
    learnMore: "കൂടുതൽ അറിയുക",
    logout: "ലോഗ്ഔട്ട്",
    selectLanguage: "നിങ്ങളുടെ ഭാഷ തിരഞ്ഞെടുക്കുക",
    welcomeTitle: "നാരിെയർ AI-ലേക്ക് സ്വാഗതം",
    welcomeSubtitle: "നിങ്ങളുടെ ആരോഗ്യ യാത്ര വ്യക്തിഗതമാക്കാൻ ഭാഷ തിരഞ്ഞെടുക്കുക.",
    navDashboard: "ഡാഷ്‌ബോർഡ്",
    navNearby: "അടുത്തുള്ള ഡോക്ടർമാർ",
    navAINavigator: "AI നാവിഗേറ്റർ",
    navTimeline: "ആരോഗ്യ രേഖകൾ",
    navReminders: "ഓർമ്മപ്പെടുത്തലുകൾ",
    navMenstrual: "ആർത്തവ പരിപാലനം",
    navPregnancy: "ഗർഭധാരണ സഹായി",
    navEducation: "ആരോഗ്യ വിദ്യാഭ്യാസം",
    navProfile: "പ്രൊഫൈൽ & ക്രമീകരണങ്ങൾ",
    goodMorning: "സുപ്രഭാതം",
    goodAfternoon: "ശുഭ ഉച്ചസമയം",
    goodEvening: "ശുഭ സായാഹ്നം",
    todaysTip: "ഇന്നത്തെ വനിതാ ആരോഗ്യ ഉപദേശം",
    nextReminder: "അടുത്ത മരുന്ന് & കുടിവെള്ള ഓർമ്മപ്പെടുത്തൽ",
    upcomingAppointment: "അടുത്ത ഡോക്ടർ അപ്പോയിന്റ്മെന്റ്",
    currentCycle: "നിലവിലെ ഘട്ടം",
    day: "ദിവസം",
    follicular: "ഫോളിക്കുലാർ ഘട്ടം",
    ovulation: "അണ്ഡോത്പാദന ഘട്ടം (Ovulation)",
    luteal: "ലൂട്ടിയൽ ഘട്ടം",
    menstrual: "ആർത്തവ ഘട്ടം",
    landing: {
      promptBanner: "നിങ്ങളുടെ ഭാഷ തിരഞ്ഞെടുക്കൂ:",
      currentlyIn: "നിലവിലെ ഭാഷ",
      changeLang: "ഭാഷ മാറ്റുക",
      heroBadge: "വനിതാ ആരോഗ്യ പ്ലാറ്റ്‌ഫോം",
      heroSub: "10 ഇന്ത്യൻ ഭാഷകളിൽ സ്ത്രീകൾക്കായുള്ള സമഗ്ര ആരോഗ്യ സേവനം.",
      goToDashboard: "ഡാഷ്‌ബോർഡിലേക്ക് പോകുക",
      safeConfidential: "സുരക്ഷിതം & രഹസ്യാത്മകം",
      indianLanguages: "ഇന്ത്യൻ ഭാഷകൾ",
      aiMedicalGuidance: "AI മെഡിക്കൽ നിർദ്ദേശം",
      verifiedFemaleDoctors: "വനിതാ ഡോക്ടർമാർ",
      connectGynaecologists: "അടുത്തുള്ള വിദഗ്ദ്ധ വനിതാ ഡോക്ടർമാരുമായി ബന്ധപ്പെടൂ",
      careEngineTitle: "സമഗ്ര പരിപാലനം",
      careEngineHeading: "സ്ത്രീകളുടെ ആരോഗ്യത്തിന് ആവശ്യമായതെല്ലാം",
      careEngineSub: "ആർത്തവം മുതൽ ഗർഭധാരണം വരെയുള്ള എല്ലാ ഘട്ടങ്ങളിലും കൂടെയുണ്ട്.",
      exploreFeature: "കൂടുതൽ അറിയുക",
      motherTongueTitle: "നിങ്ങളുടെ മാതൃഭാഷയിൽ ആരോഗ്യ സേവനങ്ങൾ",
      motherTongueSub: "മലയാളം, ഇംഗ്ലീഷ്, ഹിന്ദി തുടങ്ങിയ ഭാഷകളിൽ ഉപയോഗിക്കാം."
    },
    featureCards: {
      aiNavTitle: "AI ഹെൽത്ത് നാവിഗേറ്റർ",
      aiNavDesc: "ലക്ഷണ വിശകലനവും നിർദ്ദേശങ്ങളും.",
      nearbyTitle: "അടുത്തുള്ള ഡോക്ടർമാർ",
      nearbyDesc: "വനിതാ ഡോക്ടർമാരും ലാബ് ടെസ്റ്റുകളും.",
      timelineTitle: "ഹെൽത്ത് ടൈംലൈൻ",
      timelineDesc: "ഡിജിറ്റൽ ആരോഗ്യ രേഖകൾ.",
      remindersTitle: "സ്മാർട്ട് ഓർമ്മപ്പെടുത്തലുകൾ",
      remindersDesc: "മരുന്ന്, വെള്ളം കുടിക്കൽ ഓർമ്മപ്പെടുത്തലുകൾ.",
      menstrualTitle: "ആർത്തവ പരിപാലനം",
      menstrualDesc: "ആർത്തവ ചക്ര വിവരങ്ങൾ.",
      pregnancyTitle: "ഗർഭധാരണ സഹായി",
      pregnancyDesc: "ആഴ്ചതോറുമുള്ള വഴികാട്ടി.",
      educationTitle: "AI ആരോഗ്യ വിദ്യാഭ്യാസം",
      educationDesc: "ആരോഗ്യ ലേഖനങ്ങൾ."
    },
    cards: {
      nearby: "അടുത്തുള്ള ആരോഗ്യ സേവനങ്ങൾ കണ്ടെത്തൂ",
      nearbySub: "വനിതാ ഡോക്ടർമാർ, വീട്ടിലെ ലാബ് ടെസ്റ്റുകൾ",
      aiNav: "AI ഹെൽത്ത് നാവിഗേറ്റർ",
      aiNavSub: "തൽക്ഷണ ലക്ഷണ വിശകലനവും നിർദ്ദേശങ്ങളും",
      timeline: "ഹെൽത്ത് ടൈംലൈൻ",
      timelineSub: "ഡിജിറ്റൽ ആരോഗ്യ രേഖകളും റിപ്പോർട്ടുകളും",
      reminders: "സ്മാർട്ട് ഓർമ്മപ്പെടുത്തലുകൾ",
      remindersSub: "മരുന്ന് ഓർമ്മപ്പെടുത്തലുകളും ആർത്തവ ട്രാക്കറും",
      menstrual: "ആർത്തവ പരിപാലനം",
      menstrualSub: "ആർത്തവ ചക്ര വിവരങ്ങളും ലക്ഷണങ്ങളും",
      pregnancy: "ഗർഭധാരണ സഹായി",
      pregnancySub: "ആഴ്ചതോറുമുള്ള വഴികാട്ടി",
      pregnancyDisabledMsg: "ഗർഭധാരണം പ്ലാൻ ചെയ്യുന്നുണ്ടോ?",
      enableButton: "ആരംഭിക്കുക",
      education: "AI ആരോഗ്യ വിദ്യാഭ്യാസം",
      educationSub: "ബഹുഭാഷാ ആരോഗ്യ ലേഖനങ്ങളും ഓഡിയോയും",
      profile: "പ്രൊഫൈൽ & ക്രമീകരണങ്ങൾ",
      profileSub: "ഭാഷ, അനുമതികൾ, മുൻഗണനകൾ"
    },
    chatbot: {
      title: "നാരി AI സഹായി",
      subtitle: "വനിതാ ആരോഗ്യത്തെക്കുറിച്ച് എന്ത് വേണമെങ്കിലും ചോദിക്കൂ",
      placeholder: "നാരിയോട് ചോദിക്കൂ...",
      speaking: "നാരി സംസാരിക്കുന്നു...",
      listening: "ശ്രദ്ധിക്കുന്നു...",
      voiceInput: "സംസാരിക്കാൻ ടാപ്പ് ചെയ്യൂ",
      stopVoice: "നിർത്തൂ",
      suggestedHeader: "നിർദ്ദേശിച്ച ചോദ്യങ്ങൾ"
    }
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [currentLang, setCurrentLang] = useState(() => {
    return localStorage.getItem('naricare_lang') || 'en';
  });

  const [isLangModalOpen, setIsLangModalOpen] = useState(false);

  useEffect(() => {
    localStorage.setItem('naricare_lang', currentLang);
    // Sync user profile in localStorage if logged in
    try {
      const savedUser = localStorage.getItem('naricare_user');
      if (savedUser) {
        const parsed = JSON.parse(savedUser);
        if (parsed.preferredLanguage !== currentLang) {
          parsed.preferredLanguage = currentLang;
          localStorage.setItem('naricare_user', JSON.stringify(parsed));
        }
      }
    } catch (e) {
      console.warn('Failed to sync user preferred language in storage:', e);
    }
  }, [currentLang]);

  const changeLanguage = (langCode) => {
    if (translations[langCode] || langCode === 'en') {
      setCurrentLang(langCode);
    }
  };

  /**
   * Safe key-path lookup with English fallback.
   * Prevents undefined, raw keys, or blank text across all 10 languages.
   */
  const t = (keyPath, fallback = '') => {
    if (!keyPath) return fallback;
    const keys = keyPath.split('.');
    
    // Attempt lookup in active language
    let current = translations[currentLang];
    let foundInTarget = true;

    if (current) {
      for (const k of keys) {
        if (current && current[k] !== undefined) {
          current = current[k];
        } else {
          foundInTarget = false;
          break;
        }
      }
    } else {
      foundInTarget = false;
    }

    if (foundInTarget && current !== undefined) {
      return current;
    }

    // Fallback to English (en) dictionary
    let englishCurr = translations.en;
    let foundInEnglish = true;
    for (const k of keys) {
      if (englishCurr && englishCurr[k] !== undefined) {
        englishCurr = englishCurr[k];
      } else {
        foundInEnglish = false;
        break;
      }
    }

    if (foundInEnglish && englishCurr !== undefined) {
      return englishCurr;
    }

    // Ultimate fallback if missing in both target language and English
    return fallback || keyPath;
  };

  return (
    <LanguageContext.Provider value={{
      currentLang,
      language: currentLang, // Alias for backward compatibility
      changeLanguage,
      t,
      languages: LANGUAGES,
      isLangModalOpen,
      setIsLangModalOpen
    }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    return {
      currentLang: 'en',
      language: 'en',
      changeLanguage: () => {},
      t: (key, fallback = '') => fallback || key,
      languages: LANGUAGES,
      isLangModalOpen: false,
      setIsLangModalOpen: () => {}
    };
  }
  return context;
};
